### ISSUE TITLE
update 1btcxe functions to use correct endpoints

### ISSUE THREAD

**Issue by d3brouille** [deginner/bitcoin_exchanges#1]
1btcxe is the only exchange enabled.
# 
## ERROR: test_get_open_orders (clients.TestAPI)

Traceback (most recent call last):
  File "clients.py", line 121, in test_get_open_orders
    orders = mod.exchange.get_open_orders()
  File "/path/to/local/lib/python2.7/site-packages/bitcoin_exchanges-0.0.3-py2.7.eg/bitcoin_exchanges/1btcxe.py", line 201, in get_open_orders
    rawos = self._handle_response(self.send_request(params))
  File "/path/to/local/lib/python2.7/site-packages/bitcoin_exchanges-0.0.3-py2.7.eg/bitcoin_exchanges/1btcxe.py", line 40, in send_request
    urlpath = url + path
TypeError: cannot concatenate 'str' and 'dict' objects
# 
## ERROR: test_z_cancel_orders (clients.TestAPI)

Traceback (most recent call last):
  File "clients.py", line 81, in test_z_cancel_orders
    resp = mod.exchange.cancel_orders()
  File "/path/to/local/lib/python2.7/site-packages/bitcoin_exchanges-0.0.3-py2.7.egg/bitcoin_exchanges/1btcxe.py", line 107, in cancel_orders
    olist = self.order_list()
  File "/path/to/local/lib/python2.7/site-packages/bitcoin_exchanges-0.0.3-py2.7.egg/bitcoin_exchanges/1btcxe.py", line 239, in order_list
    return self._handle_response(self.send_request(params))
  File "/path/to/local/lib/python2.7/site-packages/bitcoin_exchanges-0.0.3-py2.7.egg/bitcoin_exchanges/1btcxe.py", line 40, in send_request
    urlpath = url + path
TypeError: cannot concatenate 'str' and 'dict' objects

**Comment by d3brouille** [comment]
the following functions are effected by this TypeError and need to be updated
- [cancel_order](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L98)
- [create_order](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L137)
- [get_info](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L195)
- [get_open_orders](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L199)
- [get_trades](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L222)
- [get_transactions](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L231)
- [order_list](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L238)
- [trade_history](https://github.com/deginner/bitcoin_exchanges/blob/unstable/bitcoin_exchanges/1btcxe.py#L245)

**Comment by d3brouille** [comment]
an initial drat of changes have been [committed](https://github.com/deginner/bitcoin_exchanges/commit/309db37ff9f1f618ae16d93f30f109232bf4ce8f).

**Comment by isysd** [comment]
Made some comments. This won't run as is, but I see there are lots of things to try when unit tests are possible again. :+1:
